language: android
jdk: oraclejdk8
env:
   global:
      - ANDROID_TARGET=android-29
      - ANDROID_ABI=armeabi-v7a
      - ANDROID_TAG=google_apis
android:
   components:
      - tools
      - tools
      - platform-tools
      - build-tools-29.0.3
      - android-29
      - extra-android-m2repository
      - sys-img-armeabi-v7a-google_apis-${ANDROID_ABI}-${ANDROID_TARGET}

before_install:
   - chmod +x gradlew
script:
   - ./gradlew build jacocoTestReport assembleAndroidTest
   - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --tag $ANDROID_TAG
   - emulator -avd test -no-skin -no-audio -no-window &
   - android-wait-for-emulator
   - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
   - ./gradlew connectedCheck
after_success:
   - bash <(curl -s https://codecov.io/bash)
